name: CI

on:
  pull_request:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: "1.15"
              otp: "25.3"
          - pair:
              elixir: "1.16"
              otp: "26.2"
            lint: lint

    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir and Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.pair.otp }}
          elixir-version: ${{ matrix.pair.elixir }}
  
      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: deps-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-

      - name: Install dependencies
        run: mix deps.get

      - name: Ensure mix.lock is up to date
        run: mix deps.get --check-locked
        if: ${{ matrix.lint }}

      - name: Ensure that files are formatted
        run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - name: Check code with credo
        run: mix credo
        if: ${{ matrix.lint }}

      - name: Run tests
        run: mix test
        if: ${{ ! matrix.lint }}

      - name: Run tests
        run: mix test --warnings-as-errors
        if: ${{ matrix.lint }}
